resource_limit: 50
resource_defaults:
  AWS::ElasticLoadBalancing::LoadBalancer: ElasticLoadBalancer
  AWS::ElasticLoadBalancingV2::TargetGroup: ApplicationELBTargetGroup
  AWS::AutoScaling::AutoScalingGroup: AutoScalingGroup
  AWS::RDS::DBInstance: RDSInstance
  AWS::RDS::DBCluster: DBCluster
  AWS::ECS::Cluster: ECSCluster
  AWS::ElastiCache::ReplicationGroup: ElastiCacheReplicationGroup
  AWS::EFS::FileSystem: ElasticFileSystem
  AWS::EC2::Instance: Ec2Instance
